### ISSUE TITLE
Привести импрот модулей к виду рекомендуемому PEP8

### ISSUE THREAD

**Issue by akhilman** [kaibruneji/MyIrcBot#4]
Согласно PEP8 желательно импортировать каждый модуль в новой строчке.
```
Yes: import os
     import sys

No:  import sys, os

It's okay to say this though:

from subprocess import Popen, PIPE
```
https://www.python.org/dev/peps/pep-0008/#imports

Так же рекомендуется сортировать импорты по алфавиту. А импорты вида `from module import object` располагать после импортов `import module`.

Ещё рекомендуется разделять импорты на отдельные блоки: в первом блоке идут стандартные модули. во втором сторонние модули не идущие в стандартной поставке питона, и в последнем блоке модули относящиеся к текущему пакету.

получится что-то вроде
```
import socket
import sys
import time
from urllib.parse import unquote

import requests
```
И да, модуль signals не используется в коде.

**Comment by kaibruneji** [comment]
Пофиксил, сенкс!
